### PR TITLE
Encoding issues solved

### PR DESCRIPTION
**Pull request by joelibaceta**
* Encoding has been solved to support ruby 1.9.2 and ruby 2.
* All test has been passed.

### CODE REVIEW

**Comment by a2800276** [comment]
Hi, sorry for the late response:

I'm currently trying to merge this. How are you running the tests? Using 'rake test' I just get a convoluted error, not sure how to make that go away to even run the tests:

Users/a2800276/.rvm/rubies/ruby-2.1.2/bin/ruby -I"lib:test:." -rubygems -I"/Users/a2800276/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib" "/Users/a2800276/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/BitmapTests.rb" "test/bla_test.rb" "test/message_test.rb" "test/test_codec.rb" "test/test_fields.rb" "test/test_seperate_msg.rb" "test/test_util.rb"
Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  /Users/a2800276/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit.rb:1:in `<top (required)>'
  /Users/a2800276/projects/ruby/8583/test/BitmapTests.rb:2:in `<top (required)>'
  /Users/a2800276/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:15:in `block in <main>'
  /Users/a2800276/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `select'
  /Users/a2800276/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `<main>'
MiniTest::Unit::TestCase is now Minitest::Test. From /Users/a2800276/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit/testcase.rb:8:in `<module:Unit>'
/Users/a2800276/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit.rb:676:in `<class:Runner>': undefined method `_run_suite' for class `Test::Unit::Runner' (NameError)
	from /Users/a2800276/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit.rb:261:in `<module:Unit>'
	from /Users/a2800276/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit.rb:15:in `<module:Test>'
	from /Users/a2800276/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit.rb:7:in `<top (required)>'
	from /Users/a2800276/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/a2800276/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/a2800276/projects/ruby/8583/test/BitmapTests.rb:2:in `<top (required)>'
	from /Users/a2800276/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/a2800276/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/a2800276/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	from /Users/a2800276/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `select'
	from /Users/a2800276/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test:." -rubygems -I"/Users/a2800276/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib" "/Users/a2800276/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/BitmapTests.rb" "test/bla_test.rb" "test/message_test.rb" "test/test_codec.rb" "test/test_fields.rb" "test/test_seperate_msg.rb" "test/test_util.rb" ]
/Users/a2800276/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/a2800276/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)

**Comment by a2800276** [comment]
Hm. So I "solved" that issue by using rvm to install clean 1.9, 2.1, 2.2.0 and 2.2.1 versions.
Still using those, versions, none of the spec run through without failure:

1.9:

```
  1) Failure:
test_hex2b(UtilTest) [/Users/a2800276/projects/ruby/8583/test/test_util.rb:8]:
<"\xAB\xCD\x12"> expected but was
<"\xAB\xCD\u0012">.

38 tests, 275 assertions, 1 failures, 0 errors, 0 skips
```

2.1.5:
```
[35/38] UtilTest#test_ascii2ebcdic = 0.00 s
  1) Failure:
UtilTest#test_ascii2ebcdic [/Users/a2800276/projects/ruby/8583/test/test_util.rb:30]:
<"\xF0\xF1\xF2\xF3\xF4\xF5\xF6\xF7\xF8\xF9"> (UTF-8) expected but was
<"\xF0\xF1\xF2\xF3\xF4\xF5\xF6\xF7\xF8\xF9"> (ASCII-8BIT).
```

2.2.0: same failure are 2.1, only more colorful

2.2.1:

```
/Users/a2800276/.rvm/rubies/ruby-2.2.1/bin/ruby -I"lib:test:." -rubygems  "/Users/a2800276/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/BitmapTests.rb" "test/bla_test.rb" "test/message_test.rb" "test/test_codec.rb" "test/test_fields.rb" "test/test_seperate_msg.rb" "test/test_util.rb"
/Users/a2800276/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- test/unit (LoadError)
	from /Users/a2800276/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/a2800276/projects/ruby/8583/test/BitmapTests.rb:2:in `<top (required)>'
	from /Users/a2800276/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/a2800276/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/a2800276/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb:15:in `block in <main>'
	from /Users/a2800276/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `select'
	from /Users/a2800276/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test:." -rubygems  "/Users/a2800276/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/BitmapTests.rb" "test/bla_test.rb" "test/message_test.rb" "test/test_codec.rb" "test/test_fields.rb" "test/test_seperate_msg.rb" "test/test_util.rb" ]
```


I find this really depressing and it's more or less the reason I think I will have to give this project up. If every single minor version change in ruby requires changing the test setup, there's no way I can support this.

Let me know if you have any ideas or if there's something I'm doing wrong (either in the test scripts or the way I run them) that's obvious to people who deal with this stuff all the time ...

(& thanks very much for your effort this far!)

**Comment by joelibaceta** [comment]
I fix this issue adding ".force_encoding('UTF-8')" in the ascii2ebcdic method.

util.rb on  line 49-51 

```
  def ascii2ebcdic(ascii)
    _conv(ascii, US_ASCII2IBM037).force_encoding('UTF-8')
  end
```

**Comment by a2800276** [comment]
I think the ASCII-8bit is the proper encoding for bytes? (actually I think there should be a 'RAW' encoding or a bytes class, it's not unheard of that programmes actually deal with bytes ...).

What do you think? I'd just change the tests and force the expected String values to ASCII...

Also: when you ran the tests against 1.9.2 everything passed? Unfortunately, rvm won't install 1.9.2 on OSX, 1.9.1 won't even start. But then 1.9.3 which I'm using has the above error ...

**Pull request merged**
